package com.behincom.behincome.Datas.Keys;

public enum FragmentState {
    Cities, Tags, Properties, ActivityResults, ActivityFields, CustomerState,
    CommissionPeriods, Products,
    VisitTours,
    Setting, AddCommissionPeriods,
    AddProducts,
    AddVisitTour,
    AddCustomer,
    BigMap,
    MainTasks,
    MainCustomers,
    MainReports,
    MainAccounts,
    MainCustomersMap,
    MainCustomerAssign,
    CustomerOnMap,
    CustomerShow,
    MainEmpty,
    Activities,
    AddFactor,
    AddTasks,
    AddTask,
    AddTasksShow,
    AddTaskSetTime,
    TaskShow,
    SetTimeEdit,
    ProfileSubmiter,
    Profile,
    Account,
    CustomerManager,
    ArchiveEnter,
    ArchiveExit,
    PersonRole,
    ContactType,
    ArchiveType,

    AddUser,
    Marketers,
    MarketerCondition,
    MarketerRole,
    MarketerAccesss,
    MarketerProfile,

    Assign,
    MarketerAccess,

}
