package com.behincom.behincome.Datas.Keys;

public enum Tables{

	BasicDatas,
	Basic_Acts,
	Basic_ActivityFieldGroups,
	Basic_ActivityFields,
	mBasic_ActivityFields,
	Basic_ActResults,
	Basic_ActivityStates,
	Basic_ActGroups,
	Basic_ArchiveTypes,
	Basic_BusinessManagerMarketerStates,
    Basic_Cities,
	Basic_CommissionTypes,
	Basic_ContactTypes,
	Basic_CustomerStates,
	Basic_CustomerStatus,
	Basic_GenderTypes,
	Basic_MaritalStatus,
	Basic_MarketerStates,
	Basic_MilitaryStatus,
	Basic_NamePrefixes,
	Basic_PersonRoles,
	Basic_PersonTypes,
	Basic_ProficiencyDegrees,
	Basic_Properties,
	mBasic_Properties,
	Basic_PropertyGroups,
	Basic_Provinces,
	Basic_TagGroups,
	Basic_Tags,
	mBasic_Tags,
	Basic_Color,
	Basic_AndroidKeyboardTypes,
	MarketingActivityFields, MarketingActResults,
	MarketingCities,
	MarketingCommissionPeriods,
	MarketingProductCommissions,
	MarketingProducts,
	MarketingProperties,
	MarketingTags,
	MarketingVisitTours,
	Keyboards,
	MarketingSetups,
}